/**
 设置公共常量
 **/

export const SET_EDITORDEF = 'SET_EDITORDEF'
export const SET_PRODEF = 'SET_PRODEF'
export const SET_LEFTSLIDER = 'SET_LEFTSLIDER'
export const SET_RIGHTSLIDER = 'SET_RIGHTSLIDER'
export const SET_COMPONENTLIST = 'SET_COMPONENTLIST'
export const SET_COMPONENTSELECTED = 'SET_COMPONENTSELECTED'
export const SET_PROPCONFIG = 'SET_PROPCONFIG'
export const CLEAR_PROPCONFIG = 'CLEAR_PROPCONFIG'
export const ADD_PROPCONFIG = 'ADD_PROPCONFIG'
export const SET_DSCONFIG = 'SET_DSCONFIG'
export const CLEAR_DSCONFIG = 'CLEAR_DSCONFIG'
export const SET_EVENTCONFIG = 'SET_EVENTCONFIG'
export const CLEAR_EVENTCONFIG = 'CLEAR_EVENTCONFIG'
export const SET_COMPONENTSDATAOBJ = 'SET_COMPONENTSDATAOBJ'
export const SET_RELOADDATA = 'SET_RELOADDATA'
